In [2]:
print("lkjflgfg")

lkjflgfg

In [3]:
symbol="BTCUSDT"
interval="1m"
limit=100


import requests

In [4]:
url = "https://api.binance.com/api/v3/klines"
params = {
    "symbol": symbol,
    "interval": interval,
    "limit": limit
}
    
response = requests.get(url, params=params)

In [7]:
data = response.json()

import pandas as pd

df = pd.DataFrame(
    data= data,
    columns=[
            'timestamp', 'open', 'high', 'low', 'close', 'volume',
            'close_time', 'quote_volume', 'trades',
            'taker_buy_base', 'taker_buy_quote', 'ignore'
        ]
)

df.head()

,timestamp,open,high,low,close,volume,close_time,quote_volume,trades,taker_buy_base,taker_buy_quote,ignore
0,1777462140000,77520.11000000,77520.11000000,77508.03000000,77515.00000000,2.18151000,1777462199999,169088.88649080,770,1.44262000,111816.30775590,0
1,1777462200000,77515.00000000,77532.75000000,77508.07000000,77532.75000000,9.59695000,1777462259999,743897.23602970,1702,5.95288000,461422.55739640,0
2,1777462260000,77532.74000000,77534.03000000,77527.74000000,77530.83000000,6.99150000,1777462319999,542068.36716590,1407,4.66257000,361500.22538050,0
3,1777462320000,77530.82000000,77541.15000000,77530.82000000,77541.14000000,8.49989000,1777462379999,659019.23199980,1399,5.61316000,435205.41424750,0
4,1777462380000,77541.15000000,77601.29000000,77541.14000000,77601.28000000,12.88016000,1777462439999,999191.55514960,2594,9.95585000,772285.92880130,0

In [8]:
! pip install ntscraper feedparser

Collecting ntscraper
  Downloading ntscraper-0.4.0-py3-none-any.whl.metadata (7.4 kB)
Collecting feedparser
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: requests>=2.28 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from ntscraper) (2.32.5)
Collecting beautifulsoup4>=4.11 (from ntscraper)
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting lxml>=4.9 (from ntscraper)
  Downloading lxml-6.1.0-cp310-cp310-win_amd64.whl.metadata (4.1 kB)
Requirement already satisfied: tqdm>=4.66 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from ntscraper) (4.67.3)
Collecting sgmllib3k (from feedparser)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting soupsieve>=1.6.1 (from beautifulsoup4>=4.11->ntscraper)
  Using cached soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from beautifulsoup4>=4.11->ntscraper) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from requests>=2.28->ntscraper) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from requests>=2.28->ntscraper) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from requests>=2.28->ntscraper) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from requests>=2.28->ntscraper) (2026.1.4)
Requirement already satisfied: colorama in c:\users\sahil\appdata\roaming\python\python310\site-packages (from tqdm>=4.66->ntscraper) (0.4.6)
Downloading ntscraper-0.4.0-py3-none-any.whl (12 kB)
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading lxml-6.1.0-cp310-cp310-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 399.0 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/4.0 MB 399.0 kB/s eta 0:00:09
   ------- -------------------------------- 0.8/4.0 MB 568.6 kB/s eta 0:00:06
   ---------- ----------------------------- 1.0/4.0 MB 671.0 kB/s eta 0:00:05
   ---------- ----------------------------- 1.0/4.0 MB 671.0 kB/s eta 0:00:05
   ------------- -------------------------- 1.3/4.0 MB 670.9 kB/s eta 0:00:05
   --------------- ------------------------ 1.6/4.0 MB 699.0 kB/s eta 0:00:04
   --------------- ------------------------ 1.6/4.0 MB 699.0 kB/s eta 0:00:04
   ------------------ --------------------- 1.8/4.0 MB 734.6 kB/s eta 0:00:03
   -------------------- ------------------- 2.1/4.0 MB 757.6 kB/s eta 0:00:03
   ----------------------- ---------------- 2.4/4.0 MB 789.3 kB/s eta 0:00:03
   -------------------------- ------------- 2.6/4.0 MB 834.0 kB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 869.2 kB/s eta 0:00:02
   ------------------------------- -------- 3.1/4.0 MB 854.4 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 886.9 kB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 886.9 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 886.5 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 918.1 kB/s  0:00:04
Using cached soupsieve-2.8.3-py3-none-any.whl (37 kB)
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (pyproject.toml): started
  Building wheel for sgmllib3k (pyproject.toml): finished with status 'done'
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6104 sha256=ecfcc1728912e9c80c10eb8eb32cf13d79e97b0ba8dad0af9a2a60e8cb651a9c
  Stored in directory: c:\users\sahil\appdata\local\pip\cache\wheels\f0\69\93\a47e9d621be168e9e33c7ce60524393c0b92ae83cf6c6e89c5
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, soupsieve, lxml, feedparser, beautifulsoup4, ntscraper

   ------ --------------------------------- 1/6 [soupsieve]
   ------------- -------------------------- 2/6 [lxml]
   ------------- -------------------------- 2/6 [lxml]
   ------------- -------------------------- 2/6 [lxml]
   ------------- -------------------------- 2/6 [lxml]
   -------------------- ------------------- 3/6 [feedparser]
   -------------------- ------------------- 3/6 [feedparser]
   -------------------- ------------------- 3/6 [feedparser]
   -------------------- ------------------- 3/6 [feedparser]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   ---------------------------------------- 6/6 [ntscraper]

Successfully installed beautifulsoup4-4.14.3 feedparser-6.0.12 lxml-6.1.0 ntscraper-0.4.0 sgmllib3k-1.0.0 soupsieve-2.8.3

In [9]:
from ntscraper import Nitter
scraper = Nitter()
tweets = scraper.get_tweets("Virat Kohli", mode='term', number=100)
# No API key, no rate limit, bilkul free

tweets

Testing instances: 100%|██████████| 9/9 [00:16<00:00,  1.86s/it]

IndexError: list index out of range

In [11]:
from ntscraper import Nitter

scraper = Nitter()  # no arguments here
tweets = scraper.get_tweets(
    "Virat Kohli",
    mode="term",
    number=100,
    instance="https://nitter.net"   # pass instance here
)

print(tweets)

Testing instances: 100%|██████████| 9/9 [00:12<00:00,  1.40s/it]

29-Apr-26 19:28:50 - Empty page on https://nitter.net
{'tweets': [], 'threads': []}

In [13]:
instances = [
    "https://nitter.poast.org",
    "https://nitter.mint.lgbt",
    "https://nitter.fdn.fr"
]

scraper = Nitter()
for inst in instances:
    try:
        tweets = scraper.get_tweets("Virat Kohli", mode="term", number=50, instance=inst)
        if tweets["tweets"]:
            print(f"Success with {inst}")
            break
    except Exception as e:
        print(f"Failed with {inst}: {e}")

Testing instances: 100%|██████████| 9/9 [00:13<00:00,  1.52s/it]

29-Apr-26 19:32:38 - Empty page on https://nitter.poast.org
Failed with https://nitter.mint.lgbt: list index out of range
Failed with https://nitter.fdn.fr: list index out of range

In [29]:
import feedparser
# BBC, Times of India, NDTV — sab ka RSS free hai
feed = feedparser.parse("https://feeds.bbci.co.uk/news/rss.xml")
articles = [entry.title + " " + entry.summary for entry in feed.entries]

articles

['Watch: Met Police body-worn footage of Golders Green arrest Footage shows the moment a man was arrested after two Jewish men were stabbed in north London.',
 'Oil price jumps after report Trump to be given new Iran options Axios reported that US Central Command has prepared a plan for a wave of "short and powerful" strikes on Iran.',
 'Neo-Nazi guilty of terror charge after MI5 sting Jurors at the Old Bailey hear Alfie Coleman, 21, believed in fighting a race war.',
 'Have the royals got their mojo back from US visit? Many commentators, even critics of the monarchy, seem delighted at the spectacle.',
 "'We will kill you and burn your house': Council staff under attack from High Street gangs Dozens of Trading Standards officers describe intimidation from criminals running mini-marts and vape shops.",
 "'Olivia's Law' gets final approval, forcing criminals to be present for sentencing hearings The legislation will force criminals to come up from their court cell and attend sentencing hearings.",
 "Statue with Banksy's signature appears in London A sculpture of a man marching off a plinth in St James's appears to bear the artist's name.",
 'Israel intercepts Gaza flotilla near Crete and detains 175 activists Pro-Palestinian activists say 22 boats carrying aid for Gaza were illegally intercepted in international waters near the Greek island.',
 'Meta in row after sacking workers who say they saw smart glasses users having sex Meta and its subcontractor disagree over why over 1000 Kenya-based workers were made redundant.',
 'Antisemitism \'a national security emergency\', government terror adviser says Home Secretary Shabana Mahmood says the issue is being treated as an "absolute priority" but does not agree it constitutes a national emergency.',
 '\'It was horrific\': Jewish security volunteers first on scene of Golders Green attack Volunteers from Shomrim describe the "pandemonium on the streets" as they rushed to help police apprehend the attacker.',
 'Who are the victims of the stabbings? Two Jewish men have been stabbed in Golders Green, north London, an attack police have declared a terrorist incident.',
 "F1's Alex Albon on getting ready for the Miami GP - and his 14 cats The Williams driver is ready to race again this weekend after the unexpected five-week break.",
 "'Being raped was a death sentence for Levi': A call for more support for survivors of sexual violence The family of the 20-year-old say her death reveals the mental torment inflicted on victims.",
 'The city caught in the middle of the big energy shift debate Is the UK fumbling the shift away from oil and gas jobs?',
 'Legal experts sceptical of DoJ case against Comey over seashell post Acting AG Todd Blanche said the case was investigated for months, adding "it\'s serious when you threaten the president."',
 "'Watershed' moment as communities gain new rights to buy important local buildings Ministers say the new law in England gives power to local people who want to help others.",
 "A son overlooked and a jailed tycoon: Inside Samsung's succession drama The family dynasty behind Samsung is so complicated it regularly makes headline news in South Korea.",
 'Watch: BBC goes inside heavily targeted US-UK base in Iraq Before the fragile ceasefire in the region, this was one of the most heavily targeted US and UK military bases in the Middle East.',
 "Smiles and wonder: How the US reacted to King Charles A divided US has come together to watch King Charles' visit with a mix of awe, delight and hope.",
 "Mamdani says he would ask King Charles to return Koh-i-Noor New York's mayor made the comments hours before meeting King Charles, but it's unclear if he brought up the diamond.",
 'In pictures: Fashion royalty meets British royalty King Charles III and Queen Camilla continued their state visit to the US by attending a ceremony at the National September 11 Memorial in New York City.',
 'What the royals did on their third day in the US After visiting the 9/11 Memorial, Queen Camilla read to children at the New York Public Library and King Charles visited a community organisation in Harlem.',
 'King and Queen lay flowers at 9/11 Memorial in New York King Charles and Queen Camilla on their state visit to the US visit the memorial in New York.',
 'Bob Mortimer saddened by death of Gone Fishing dog Ted first appeared in Mortimer and Whitehouse: Gone Fishing in 2020 and became popular with fans.',
 'Endometriosis could be diagnosed earlier with new scan technique A new scan technique could spot areas of endometriosis missed by conventional scans, scientists say.',
 'Farringdon station reopens after possible gas leak A small number of passengers reported feeling unwell, British Transport Police said.',
 'Saudi Arabia to stop funding LIV Golf next season Saudi Arabia will withdraw its multi-billion dollar backing of LIV Golf at the end of the season, plunging the future of the series into doubt.',
 'Video that police denied existed shows woman pinned down Nadine Buzzard-Quashie speaks for first time about her "David and Goliath battle" against two police forces.',
 'BBC News app Top stories, breaking news, live reporting, and follow news topics that match your interests',
 'What The King Did (And Didn’t) Say To Trump Decoding what the King said to President Trump.',
 "Who is Trump’s 'would-be assassin' and were there security failings at DC shooting? The US president was evacuated from the White House Correspondents Dinner",
 'Burnley want Bellamy after Parker leaves Burnley are interested in appointing Craig Bellamy as manager after Scott Parker leaves following relegation from the Premier League.',
 'Saudi Arabia to stop funding LIV Golf at end of season Saudi Arabia will withdraw its multi-billion dollar backing of LIV Golf at the end of the season, plunging the future of the series into doubt.',
 'Mainoo signs new Man Utd deal until 2031 Kobbie Mainoo signs a new contract with Manchester United that will keep him at Old Trafford until 2031.',
 "Lomu, Wilkinson, Pollock? Rugby's search for a crossover star Henry Pollock has signed with Eddie Hearn's talent agency in the hope of boosting his profile, but why has rugby found it so hard to forge mainstream figureheads?",
 "The 92mph England fast bowler ready to move on from difficult debut A stronger and faster Sonny Baker is ready to put last summer's difficult white-ball debuts for England behind him.",
 'England captain Williamson extends 20-year Arsenal stay Leah Williamson is the fourth player to commit her future to the club in recent weeks, with Kim Little, Stina Blackstenius, and Steph Catley also signing new deals.']

In [32]:
sentiment_pipeline(articles[0])[0]['label']

'NEGATIVE'

In [ ]:
from transformers import pipeline

sentiment_pipeline = pipeline("sentiment-analysis")

comments = ["I love this video!", "This is boring."]
results = sentiment_pipeline(comments)

for c, r in zip(comments, results):
    print(c, "->", r["label"])

C:\Users\sahil\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

29-Apr-26 19:45:27 - HTTP Request: HEAD https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english/resolve/714eb0f/config.json "HTTP/1.1 307 Temporary Redirect"

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

29-Apr-26 19:45:27 - Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
29-Apr-26 19:45:27 - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/714eb0fa89d2f80546fda750413ed43d93601a13/config.json "HTTP/1.1 200 OK"
29-Apr-26 19:45:27 - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/714eb0fa89d2f80546fda750413ed43d93601a13/config.json "HTTP/1.1 200 OK"

d:\mlops\Crypto_Guardian\venv\lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sahil\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

29-Apr-26 19:45:27 - HTTP Request: HEAD https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english/resolve/714eb0f/model.safetensors "HTTP/1.1 302 Found"
29-Apr-26 19:45:28 - HTTP Request: GET https://huggingface.co/api/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/xet-read-token/714eb0fa89d2f80546fda750413ed43d93601a13 "HTTP/1.1 200 OK"

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 5409.66it/s]

29-Apr-26 19:48:49 - HTTP Request: HEAD https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english/resolve/714eb0f/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
29-Apr-26 19:48:49 - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/714eb0fa89d2f80546fda750413ed43d93601a13/tokenizer_config.json "HTTP/1.1 200 OK"
29-Apr-26 19:48:50 - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/714eb0fa89d2f80546fda750413ed43d93601a13/tokenizer_config.json "HTTP/1.1 200 OK"
29-Apr-26 19:48:50 - HTTP Request: GET https://huggingface.co/api/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/tree/714eb0f/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
29-Apr-26 19:48:50 - HTTP Request: GET https://huggingface.co/api/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
29-Apr-26 19:48:51 - HTTP Request: HEAD https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english/resolve/714eb0f/vocab.txt "HTTP/1.1 307 Temporary Redirect"
29-Apr-26 19:48:51 - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/714eb0fa89d2f80546fda750413ed43d93601a13/vocab.txt "HTTP/1.1 200 OK"
29-Apr-26 19:48:51 - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/714eb0fa89d2f80546fda750413ed43d93601a13/vocab.txt "HTTP/1.1 200 OK"
29-Apr-26 19:48:51 - HTTP Request: HEAD https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english/resolve/714eb0f/tokenizer.json "HTTP/1.1 404 Not Found"
29-Apr-26 19:48:52 - HTTP Request: HEAD https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english/resolve/714eb0f/added_tokens.json "HTTP/1.1 404 Not Found"
29-Apr-26 19:48:52 - HTTP Request: HEAD https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english/resolve/714eb0f/special_tokens_map.json "HTTP/1.1 404 Not Found"
29-Apr-26 19:48:53 - HTTP Request: HEAD https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english/resolve/714eb0f/chat_template.jinja "HTTP/1.1 404 Not Found"
I love this video! -> POSITIVE
This is boring. -> NEGATIVE

In [20]:
articles

["Will King's US visit lead to lasting reset in relations with UK? As applause fades and banquet plates are cleared, it's up to politicians to build on Charles's historic trip.",
 "Nine held in religious group modern slavery raid Up to 500 officers are involved in three raids at Crewe's Ahmadi Religion of Peace and Light group.",
 "Eleven cancers on the rise in young people - scientists find first clue on why it's happening Researchers stress that simple lifestyle changes can still significantly reduce the risk of cancer.",
 "University of Sussex wins court challenge to overturn £585,000 freedom of speech fine A record fine had been issued by the Office for Students over the university's trans and non-binary inclusion policy.",
 'Farage received £5m from donor before he became MP The Reform leader says the gift was for his personal security - but opponents say he should have declared it.',
 'William and Catherine share new photo to mark 15th wedding anniversary The photo shows William and Catherine lying in grass with their children, Prince George, Princess Charlotte and Prince Louis.',
 'PM defends record as Badenoch says he squandered election win The prime minister and Conservative leader argue over welfare and defence spending ahead of May elections.',
 "Oil price jumps to nearly $117 after reports of 'extended' Iran blockade The price of crude oil has swung sharply as uncertainty over the war in the Middle East continues.",
 'Tupac\'s family files wrongful death lawsuit in LA The suit seeks to uncover several "co-conspirators" who may have been involved in the star\'s death.',
 'Irish government announces further fuel supports after protests The Irish government has announced further fuel supports for a number of sectors after nationwide protests in recent weeks.',
 'Laura Dern replaces Helena Bonham Carter in The White Lotus The British actress left the hit show due to creative differences shortly after filming began.',
 "The diplomacy at play behind the King's speeches How King Charles III navigated a diplomatic tightrope in his speech to the US Congress.",
 "'If it wasn't for us, you'd be speaking French': King jokes at White House dinner The King and the US president exchanged several jokes during their speeches at a state banquet.",
 'Fashion, billionaires and jokes: Inside the White House state dinner The night was filled with designer fashion, luscious bouquets, billionaire guests and joke-filled speeches.',
 'The state visit in pictures King Charles III and Queen Camilla continued their state visit to the US with a White House state dinner and a speech from the King to Congress.',
 "I shouldn't have been made to visit abusive killer mum Kelly Higgins said despite her mother being in jail for murder, she retained rights over her.",
 "A fresh financial crisis may be coming - it won't play out like the last one Several warning lights are flashing that have some wondering whether we are in the foothills of another financial crisis.",
 'Why has the UAE left Opec - and why does this matter? The United Arab Emirates (UAE) is quitting oil cartel Opec after nearly 60 years of membership.',
 'OCD made me think I was a monster Sufferers explain how the condition has gripped their lives - but say help is out there.',
 '£20m mystery donation buys London Zoo new hospital where you can watch vets work Visitors will be able to watch live veterinary procedures inside a state-of-the-art new animal hospital.',
 'Should I Marry a Murderer? - the love story that uncovered a killer True crime show follows a woman facing a life-changing dilemma after her fiancé makes a shock confession.',
 "Record labels rejected her - but Julia Wolf's gothic pop is on the rise Wolf's song In My Room exploded on TikTok after being paired with clips from the Twilight movies.",
 'Russia scales back Moscow Victory Day parade, blaming threat from Ukraine Russia says the annual commemoration of Soviet victory in World War Two will not feature military vehicles or cadets.',
 'Man offered Ukrainians money to carry out Starmer arson attacks, court hears The three men are accused of targeting north London properties linked to Prime Minister Sir Keir Starmer.',
 'Global forest loss slows but El Niño fires could threaten progress The loss of tropical rainforests eased last year, according to new analysis, but scientists warn they are still disappearing rapidly.',
 "Israeli 'double-tap' strike kills three rescue workers in Lebanon, officials say They are among five people officials say were killed in successive attacks on Tuesday.",
 "Russian paramilitary carried out air strikes in Mali as rebels advanced, footage shows Last weekend's attacks came as the Africa Corps withdrew from a key base in northern Mali.",
 "Mum who blamed another child for her baby's death found guilty of murder Nicole Blain's 19-day-old daughter Thea Wilson had suffered broken ribs and three skull fractures.",
 'Chelsea captain Bright retires - what now for ex-England defender? Chelsea captain Millie Bright announces she has retired from football with immediate effect because of injury.',
 'BBC News app Top stories, breaking news, live reporting, and follow news topics that match your interests',
 'The Morgan McSweeney Evidence And, MPs vote against Starmer facing parliamentary inquiry over Mandelson vetting.',
 "Who is Trump’s 'would-be assassin' and were there security failings at DC shooting? The US president was evacuated from the White House Correspondents Dinner",
 "'Joshua warm-up defeat would scupper Fury fight' The long-awaited showdown between Tyson Fury and Anthony Joshua will not happen if Joshua loses his July warm-up bout, says promoter Frank Warren.",
 'Chelsea captain Bright retires - what now for ex-England defender? Chelsea captain Millie Bright announces she has retired from football with immediate effect because of injury.',
 "Will Rose's McLaren club gamble pay off? Justin Rose will use his new McLaren Golf clubs in competition for the first time this week. What are the risks of his partnership with the Formula 1 team?",
 "Can Griezmann end his Atletico love story in style? Antoine Griezmann's long love affair with Atletico Madrid is drawing to a close, but can the Frenchman bid farewell by securing the Champions League?",
 'Pimblett blames ego for UFC loss to Gaethje Paddy Pimblett reflects on his loss to Justin Gaethje as he returns to camp for his comeback fight in July.',
 'Former NFL player Mauro dies aged 35 Former Arizona Cardinals defensive end Josh Mauro dies at the age of 35.']

In [19]:
from transformers import pipeline

sentiment_pipeline = pipeline("sentiment-analysis")
dict ={}
feed = feedparser.parse("https://feeds.bbci.co.uk/news/rss.xml")
for articles in [entry.title + " " + entry.summary for entry in feed.entries]:
    dict[articles] = sentiment_pipeline(articles)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
Loading weights: 100%|██████████| 104/104 [00:00<00:00, 2681.02it/s]

In [2]:

rss_feeds = [
    "https://feeds.bbci.co.uk/news/rss.xml",
    "https://feeds.bbci.co.uk/news/world/rss.xml",
    "https://feeds.bbci.co.uk/news/technology/rss.xml",
    "https://feeds.bbci.co.uk/news/business/rss.xml"
]

# rss_feeds = [
#     # 📰 BBC (Core)
#     "https://feeds.bbci.co.uk/news/rss.xml",
#     "https://feeds.bbci.co.uk/news/world/rss.xml",
#     "https://feeds.bbci.co.uk/news/technology/rss.xml",
#     "https://feeds.bbci.co.uk/news/business/rss.xml",
#     "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
#     "https://feeds.bbci.co.uk/news/health/rss.xml",
#     "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",

#     # 🌍 Google News (Dynamic 🔥)
#     "https://news.google.com/rss/search?q=india",
#     "https://news.google.com/rss/search?q=technology",
#     "https://news.google.com/rss/search?q=stock+market",
#     "https://news.google.com/rss/search?q=AI",
#     "https://news.google.com/rss/search?q=politics",

#     # 🇮🇳 Indian News
#     "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
#     "https://www.thehindu.com/news/feeder/default.rss",
#     "https://www.ndtv.com/rss",
#     "https://indianexpress.com/feed/",
#     "https://www.hindustantimes.com/feeds/rss/topnews/rssfeed.xml",

#     # 🌐 Global News
#     "https://rss.cnn.com/rss/edition.rss",
#     "https://feeds.skynews.com/feeds/rss/world.xml",
#     "https://www.aljazeera.com/xml/rss/all.xml",
#     "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best",
#     "https://feeds.npr.org/1001/rss.xml",

#     # 💻 Tech News
#     "https://techcrunch.com/feed/",
#     "https://www.theverge.com/rss/index.xml",
#     "https://www.wired.com/feed/rss",

#     # 💰 Finance
#     "https://www.moneycontrol.com/rss/latestnews.xml",
#     "https://feeds.marketwatch.com/marketwatch/topstories/",
# ]
import feedparser
import pandas as pd
from transformers import pipeline

import torch

# Automatically check if GPU is available
# device=0 matlab GPU, device=-1 matlab CPU
device = 0 if torch.cuda.is_available() else -1

print(f"Using device: {'GPU' if device == 0 else 'CPU'}")

# Pipeline initialization with device
sentiment_pipeline = pipeline("sentiment-analysis", device=device)

# sentiment_pipeline = pipeline("sentiment-analysis")
# dict ={}

articless = {}
for url in rss_feeds:
    feed = feedparser.parse(url)

    for entry in feed.entries:
        data=entry.title + " " + entry.summary
        # print(data)
        articless[data]=sentiment_pipeline(data)[0]['label']
        # print("_"*20)
        # articless.append()


# print(articless[1])
# articless
df = pd.DataFrame(data=articless.items(),columns=['text','label'])

df.to_csv("sample_data.csv")

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Using device: CPU

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 104/104 [00:00<00:00, 4145.67it/s]

In [1]:
import feedparser
import pandas as pd
from transformers import pipeline

rss_feeds = [
    "https://feeds.bbci.co.uk/news/rss.xml",
    "https://feeds.bbci.co.uk/news/world/rss.xml",
    "https://feeds.bbci.co.uk/news/technology/rss.xml",
    "https://feeds.bbci.co.uk/news/business/rss.xml"
]


# 1. Initialize the pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

# 2. Collect data into a list of dictionaries
raw_data = []
for url in rss_feeds:
    feed = feedparser.parse(url)
    for entry in feed.entries:
        # Use .get() to avoid KeyErrors if summary is missing
        title = entry.get('title', '')
        summary = entry.get('summary', '')
        full_text = f"{title} {summary}".strip()
        
        if full_text:
            raw_data.append({"text": full_text})

# 3. Batch process sentiments (Much faster!)
texts = [item['text'] for item in raw_data]
results = sentiment_pipeline(texts)

# 4. Merge results back and create DataFrame
for i, result in enumerate(results):
    raw_data[i]['label'] = result['label']
    raw_data[i]['score'] = result['score'] # Added score for better insights

df = pd.DataFrame(raw_data)

# 5. Export
df.to_csv("sample_data.csv", index=False)

C:\Users\sahil\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
Loading weights: 100%|██████████| 104/104 [00:00<00:00, 3101.59it/s]

In [6]:
df.shape

(1172, 2)

In [14]:
# Isse ensure hoga ki sab string hai, jo non-string hoga wo NaN ban jayega
df['label'] = df['label'].astype(str)

In [16]:
df['label'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 116 entries, 0 to 115
Series name: label
Non-Null Count  Dtype
--------------  -----
116 non-null    object
dtypes: object(1)
memory usage: 1.0+ KB

In [11]:
df['label'].value_counts(normalize=True)

label
NEGATIVE    0.75
POSITIVE    0.25
Name: proportion, dtype: float64

In [13]:
print(df['label'].unique()) 
# Output should be only: ['POSITIVE', 'NEGATIVE']

['NEGATIVE' 'POSITIVE']

In [28]:
df =  pd.DataFrame(dict)
df.head()

,"Israel-US और Iran युद्ध तेज, दुबई में धमाकों से मचा हड़कंप; Hormuz Strait पर संकट से तेल-गैस सप्लाई पर खतरा <p>मिडिल ईस्ट में बढ़ते तनाव के बीच दुबई में मिसाइल के मलबे से धमाका, ईरान ने Hormuz Strait पर नियंत्रण सख्त किया मिडिल ईस्ट में अमेरिका-इजरायल और ईरान के बीच चल रहे युद्ध ने अब गंभीर रूप ले लिया है। हालात इतने तनावपूर्ण हो गए हैं कि कई खाड़ी देशों तक इसका असर दिखाई देने [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/israel-us-iran-war-blasts-shake-dubai-hormuz-strait-crisis-threatens-global-oil-supply/"">Israel-US और Iran युद्ध तेज, दुबई में धमाकों से मचा हड़कंप; Hormuz Strait पर संकट से तेल-गैस सप्लाई पर खतरा</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>","पाकिस्तानी स्पिनर अबरार अहमद के पुराने एंटी-इंडिया पोस्ट वायरल, काव्या मारन की टीम पर उठे सवाल <p>द हंड्रेड’ लीग में पाकिस्तानी खिलाड़ी को खरीदने के बाद विवाद बढ़ा, सोशल मीडिया पर फैंस ने जताई नाराजगी इंग्लैंड की मशहूर क्रिकेट लीग “द हंड्रेड” के 2026 सीजन के ऑक्शन के बाद एक बड़ा विवाद सामने आया है। पाकिस्तान के मिस्ट्री स्पिनर अबरार अहमद को सन ग्रुप के स्वामित्व वाली टीम सनराइजर्स लीड्स ने [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/old-anti-india-posts-of-pakistan-spinner-abrar-ahmed-go-viral-questions-raised-on-kavya-marans-team/"">पाकिस्तानी स्पिनर अबरार अहमद के पुराने एंटी-इंडिया पोस्ट वायरल, काव्या मारन की टीम पर उठे सवाल</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>","Big Boost to India’s Tech Dreams First Major Semiconductor Plant in North India Coming to Greater Noida! <p>In a major step toward strengthening India’s electronics manufacturing base, the foundation stone for North India’s first semiconductor manufacturing unit will be laid on 21 February 2026 in Sector-28, Yamuna City area, Greater Noida. What’s Happening? Inauguration Event What Will the Plant Do? Investment &#38; Jobs Strategic Importance This project is a key part of [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/big-boost-to-indias-tech-dreams-first-major-semiconductor-plant-in-north-india-coming-to-greater-noida/"">Big Boost to India’s Tech Dreams First Major Semiconductor Plant in North India Coming to Greater Noida!</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>","CM Yuva Yojana: Uttar Pradesh Offers Up to ₹10 Lakh Interest-Free Support for Young Entrepreneurs <p>The CM Yuva Yojana (Chief Minister Youth Entrepreneur Development Scheme) launched by the Government of Uttar Pradesh is designed to empower young people to build their own businesses instead of depending solely on jobs. Through this initiative, eligible youth can receive financial assistance of up to ₹10 lakh, largely interest-free and without collateral, making it [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/cm-yuva-yojana-uttar-pradesh-offers-up-to-%e2%82%b910-lakh-interest-free-support-for-young-entrepreneurs/"">CM Yuva Yojana: Uttar Pradesh Offers Up to ₹10 Lakh Interest-Free Support for Young Entrepreneurs</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>","GPU as a Service (GaaS): The Complete 2026 Guide to High-Performance Computing in the Cloud <p>The demand for extreme computational power has surged in recent years as artificial intelligence, machine learning, high-performance computing (HPC), 3D rendering, and gaming workloads continue to grow exponentially. Traditional CPU-based infrastructure is no longer sufficient for these compute-intensive tasks—which is why GPU as a Service has become a critical technology in 2026. GPU as a [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/gpu-as-a-service-gaas-the-complete-2026-guide-to-high-performance-computing-in-the-cloud/"">GPU as a Service (GaaS): The Complete 2026 Guide to High-Performance Computing in the Cloud</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>","How AI Chatbot Solutions Are Transforming Customer Support in 2026 <p>Customer support has changed more in the past three years than in the previous two decades, and AI chatbot solutions sit right at the center of this transformation. In 2026, businesses of all sizes—from startups to global enterprises—are using AI-driven support systems to deliver faster, smarter, and more personalized customer service. What used to be [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/how-ai-chatbot-solutions-are-transforming-customer-support-in-2026/"">How AI Chatbot Solutions Are Transforming Customer Support in 2026</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>","The Growing Role of Serverless Inferencing in AI Deployment <p>In recent years, artificial intelligence (AI) has moved from research labs into enterprise applications, consumer products, and real-time decision-making systems. As organizations adopt AI at scale, the challenge often shifts from model training to deployment and inference. Deploying models in production requires handling unpredictable workloads, optimizing costs, and ensuring low-latency responses. Traditional infrastructure approaches, however, [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/the-growing-role-of-serverless-inferencing-in-ai-deployment/"">The Growing Role of Serverless Inferencing in AI Deployment</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>","Serverless Inferencing: Revolutionizing Scalable and Efficient AI Deployments <p>In the evolving world of artificial intelligence, delivering fast, scalable, and cost-effective inference has become a critical challenge. Traditional inference architectures, reliant on fixed GPU clusters or dedicated infrastructure, often lead to underutilization, high costs, and operational complexities. Enter serverless inferencing — a transformative approach that is redefining how AI models are deployed and served [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/serverless-inferencing-revolutionizing-scalable-and-efficient-ai-deployments/"">Serverless Inferencing: Revolutionizing Scalable and Efficient AI Deployments</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>","4 Picks That Let Women Rock the Look <p>Every woman should own pieces that empower her, and help her feel confident, stylish, and genuinely her own. When good looks meet smart designs, everyday dressing becomes carefree and fun. You don&#8217;t need a lot of things to make a statement; just the right picks do it all. From polished pumps to smart add-ons, thoughtful [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/4-picks-that-let-women-rock-the-look/"">4 Picks That Let Women Rock the Look</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>","Cyfuture Joins IndiaAI Mission with 34,000+ GPUs for AI Growth <p>Cyfuture joins the mission to Make AI in India and Make AI Work for India, proudly contributing to the nation&#8217;s AI revolution with over 34,000+ GPUs now powering India’s AI future. We’re honoured that Cyfuture AI has been empanelled under the IndiaAI Compute Initiative to deliver AI Compute Services, playing a pivotal role in enabling [&#8230;]</p>\n<p>The post <a href=""https://www.abcrnews.com/cyfuture-joins-indiaai-mission-with-34000-gpus-for-ai-growth/"">Cyfuture Joins IndiaAI Mission with 34,000+ GPUs for AI Growth</a> appeared first on <a href=""https://www.abcrnews.com"">AbcrNews</a>.</p>"
0,"{'label': 'NEGATIVE', 'score': 0.9878078103065...","{'label': 'NEGATIVE', 'score': 0.9789682030677...","{'label': 'POSITIVE', 'score': 0.9969196319580...","{'label': 'NEGATIVE', 'score': 0.8053103685379...","{'label': 'NEGATIVE', 'score': 0.9952602982521...","{'label': 'POSITIVE', 'score': 0.9854084849357...","{'label': 'POSITIVE', 'score': 0.5393964052200...","{'label': 'NEGATIVE', 'score': 0.9129099249839...","{'label': 'POSITIVE', 'score': 0.9992790818214...","{'label': 'POSITIVE', 'score': 0.9959661960601..."

In [17]:
dict= {}

dict["man"] = "hello"
dict.append()
dict

{'man': 'hello'}

In [52]:
! pip install snscrape

Collecting snscrape
  Downloading snscrape-0.7.0.20230622-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: requests[socks] in c:\users\sahil\appdata\roaming\python\python310\site-packages (from snscrape) (2.32.5)
Requirement already satisfied: lxml in d:\mlops\crypto_guardian\venv\lib\site-packages (from snscrape) (6.1.0)
Requirement already satisfied: beautifulsoup4 in d:\mlops\crypto_guardian\venv\lib\site-packages (from snscrape) (4.14.3)
Requirement already satisfied: filelock in d:\mlops\crypto_guardian\venv\lib\site-packages (from snscrape) (3.29.0)
Requirement already satisfied: soupsieve>=1.6.1 in d:\mlops\crypto_guardian\venv\lib\site-packages (from beautifulsoup4->snscrape) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from beautifulsoup4->snscrape) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from requests[socks]->snscrape) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from requests[socks]->snscrape) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from requests[socks]->snscrape) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from requests[socks]->snscrape) (2026.1.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\sahil\appdata\roaming\python\python310\site-packages (from requests[socks]->snscrape) (1.7.1)
Downloading snscrape-0.7.0.20230622-py3-none-any.whl (74 kB)
Installing collected packages: snscrape
Successfully installed snscrape-0.7.0.20230622

In [54]:
import snscrape.modules.twitter as sntwitter
tweets = []
query = "india"
limit = 50
search_query = f"{query} lang:en"

for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_query).get_items()):
    if i >= limit:
        break
    
    tweets.append({

        "content": tweet.content

    })

30-Apr-26 18:34:50 - Retrieving scroll page None
30-Apr-26 18:34:50 - Retrieving guest token
30-Apr-26 18:34:50 - Retrieving https://twitter.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click

30-Apr-26 18:34:52 - Retrieved https://twitter.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click (redirected to https://x.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click): 200
30-Apr-26 18:34:52 - Retrieving guest token via API
30-Apr-26 18:34:52 - Retrieving https://api.twitter.com/1.1/guest/activate.json
30-Apr-26 18:34:54 - Retrieved https://api.twitter.com/1.1/guest/activate.json: 200
30-Apr-26 18:34:54 - Retrieving https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D
30-Apr-26 18:34:54 - Retrieved https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D: 404
30-Apr-26 18:34:54 - Retrieving guest token
30-Apr-26 18:34:54 - Retrieving https://twitter.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click
30-Apr-26 18:34:56 - Retrieved https://twitter.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click (redirected to https://x.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click): 200
30-Apr-26 18:34:56 - Retrieving guest token via API
30-Apr-26 18:34:56 - Retrieving https://api.twitter.com/1.1/guest/activate.json
30-Apr-26 18:34:56 - Retrieved https://api.twitter.com/1.1/guest/activate.json: 200
30-Apr-26 18:34:56 - Error retrieving https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D: blocked (404), retrying
30-Apr-26 18:34:56 - Waiting 1 seconds
30-Apr-26 18:34:57 - Retrieving https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D
30-Apr-26 18:34:58 - Retrieved https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D: 404
30-Apr-26 18:34:58 - Retrieving guest token
30-Apr-26 18:34:58 - Retrieving https://twitter.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click
30-Apr-26 18:35:00 - Retrieved https://twitter.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click (redirected to https://x.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click): 200
30-Apr-26 18:35:00 - Retrieving guest token via API
30-Apr-26 18:35:00 - Retrieving https://api.twitter.com/1.1/guest/activate.json
30-Apr-26 18:35:01 - Retrieved https://api.twitter.com/1.1/guest/activate.json: 200
30-Apr-26 18:35:01 - Error retrieving https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D: blocked (404), retrying
30-Apr-26 18:35:01 - Waiting 2 seconds
30-Apr-26 18:35:03 - Retrieving https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D
30-Apr-26 18:35:03 - Retrieved https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D: 404
30-Apr-26 18:35:03 - Retrieving guest token
30-Apr-26 18:35:03 - Retrieving https://twitter.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click
30-Apr-26 18:35:06 - Retrieved https://twitter.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click (redirected to https://x.com/search?f=live&lang=en&q=india+lang%3Aen&src=spelling_expansion_revert_click): 200
30-Apr-26 18:35:06 - Retrieving guest token via API
30-Apr-26 18:35:06 - Retrieving https://api.twitter.com/1.1/guest/activate.json
30-Apr-26 18:35:07 - Retrieved https://api.twitter.com/1.1/guest/activate.json: 200
30-Apr-26 18:35:07 - Error retrieving https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D: blocked (404), retrying
30-Apr-26 18:35:07 - Waiting 4 seconds
30-Apr-26 18:35:11 - Retrieving https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D

ScraperException: 4 requests to https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22india%20lang%3Aen%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D failed, giving up.